-- Initial schema for ABRAZO Health Guardian.
-- Extracted verbatim from docs/context.md, section 11 (Database Schema).

-- ============================================================
-- 11.1 Users & Authentication
-- ============================================================

-- Extended user profiles (extends Supabase auth.users)
CREATE TABLE user_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  full_name TEXT NOT NULL,
  date_of_birth DATE,
  gender TEXT CHECK (gender IN ('male', 'female', 'other', 'prefer_not_to_say')),
  blood_type TEXT,
  height_cm INTEGER,
  weight_kg DECIMAL(5,2),
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  emergency_contact_relation TEXT,
  profile_image_url TEXT,
  language_preference TEXT DEFAULT 'en',
  theme_preference TEXT DEFAULT 'light' CHECK (theme_preference IN ('light', 'dark', 'auto')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- User settings
CREATE TABLE user_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  notification_medicine_reminders BOOLEAN DEFAULT true,
  notification_consultation_reminders BOOLEAN DEFAULT true,
  notification_health_alerts BOOLEAN DEFAULT true,
  notification_ble_status BOOLEAN DEFAULT true,
  data_sync_frequency_minutes INTEGER DEFAULT 5,
  emergency_number TEXT DEFAULT '911',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id)
);

-- ============================================================
-- 11.2 BLE Devices
-- ============================================================

-- Registered BLE devices
CREATE TABLE ble_devices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  device_name TEXT NOT NULL,
  device_mac_address TEXT NOT NULL,
  device_type TEXT NOT NULL CHECK (device_type IN ('bp_monitor', 'heart_rate', 'spo2', 'smartwatch', 'temperature', 'ecg', 'other')),
  device_brand TEXT,
  device_model TEXT,
  is_connected BOOLEAN DEFAULT false,
  battery_level INTEGER,
  last_connected_at TIMESTAMPTZ,
  last_sync_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, device_mac_address)
);

-- Health metrics readings
CREATE TABLE health_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  device_id UUID REFERENCES ble_devices(id) ON DELETE SET NULL,
  metric_type TEXT NOT NULL CHECK (metric_type IN ('blood_pressure', 'heart_rate', 'spo2', 'temperature', 'respiration', 'steps', 'ecg', 'glucose', 'weight', 'other')),
  systolic INTEGER, -- For BP
  diastolic INTEGER, -- For BP
  value DECIMAL(10,2), -- For single-value metrics
  unit TEXT, -- 'bpm', '%', '°C', 'mmHg', etc.
  notes TEXT,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Health alerts generated by AI
CREATE TABLE health_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  alert_type TEXT NOT NULL CHECK (alert_type IN ('critical', 'warning', 'info')),
  severity TEXT NOT NULL CHECK (severity IN ('red', 'yellow', 'green')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  related_metric_ids UUID[], -- Array of health_metrics IDs
  ai_analysis TEXT, -- AI-generated explanation
  recommended_action TEXT,
  is_read BOOLEAN DEFAULT false,
  is_resolved BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

-- ============================================================
-- 11.3 Consultations
-- ============================================================

-- Doctor specialties
CREATE TABLE specialties (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  icon_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Doctors
CREATE TABLE doctors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  specialty_id UUID NOT NULL REFERENCES specialties(id),
  qualification TEXT,
  experience_years INTEGER,
  hospital_clinic_name TEXT,
  location TEXT,
  phone TEXT,
  email TEXT,
  profile_image_url TEXT,
  consultation_fee DECIMAL(10,2),
  is_available BOOLEAN DEFAULT true,
  rating DECIMAL(3,2) DEFAULT 0.0,
  total_reviews INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Consultations/Appointments
CREATE TABLE consultations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  doctor_id UUID NOT NULL REFERENCES doctors(id),
  specialty_id UUID NOT NULL REFERENCES specialties(id),
  appointment_date DATE NOT NULL,
  appointment_time TIME NOT NULL,
  duration_minutes INTEGER DEFAULT 30,
  consultation_type TEXT NOT NULL CHECK (consultation_type IN ('in_person', 'online', 'phone')),
  location TEXT, -- For in-person
  meeting_link TEXT, -- For online
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled', 'no_show')),
  reason TEXT,
  notes TEXT,
  prescription_id UUID, -- Reference to prescription if generated
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  cancelled_at TIMESTAMPTZ
);

-- ============================================================
-- 11.4 Medical Records
-- ============================================================

-- Medical records
CREATE TABLE medical_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  record_type TEXT NOT NULL CHECK (record_type IN ('lab_report', 'prescription', 'discharge_summary', 'xray', 'scan', 'other')),
  title TEXT NOT NULL,
  description TEXT,
  file_url TEXT, -- Supabase Storage URL
  file_type TEXT, -- 'pdf', 'image', etc.
  file_size_bytes BIGINT,
  extracted_text TEXT, -- AI-extracted text from OCR
  doctor_name TEXT,
  hospital_clinic_name TEXT,
  record_date DATE,
  tags TEXT[], -- Array of tags for categorization
  is_important BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 11.5 Medicines
-- ============================================================

-- Medicine catalog (master data)
CREATE TABLE medicine_catalog (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  generic_name TEXT,
  manufacturer TEXT,
  dosage_form TEXT, -- 'tablet', 'capsule', 'syrup', etc.
  strength TEXT, -- '500mg', '10ml', etc.
  description TEXT,
  image_url TEXT,
  is_prescription_required BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User's current medicines
CREATE TABLE user_medicines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  medicine_catalog_id UUID REFERENCES medicine_catalog(id),
  medicine_name TEXT NOT NULL, -- Custom name if not in catalog
  dosage TEXT NOT NULL, -- '1 tablet', '10ml', etc.
  frequency TEXT NOT NULL, -- 'once_daily', 'twice_daily', 'thrice_daily', 'as_needed', 'custom'
  custom_schedule JSONB, -- For complex schedules
  start_date DATE NOT NULL,
  end_date DATE, -- NULL for ongoing medicines
  quantity_total INTEGER,
  quantity_remaining INTEGER,
  notes TEXT,
  prescribed_by_doctor_id UUID REFERENCES doctors(id),
  consultation_id UUID REFERENCES consultations(id),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Medicine reminders
CREATE TABLE medicine_reminders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_medicine_id UUID NOT NULL REFERENCES user_medicines(id) ON DELETE CASCADE,
  reminder_time TIME NOT NULL,
  days_of_week INTEGER[], -- [0=Sunday, 1=Monday, ..., 6=Saturday] or NULL for daily
  is_active BOOLEAN DEFAULT true,
  last_triggered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Medicine intake log
CREATE TABLE medicine_intake_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_medicine_id UUID NOT NULL REFERENCES user_medicines(id) ON DELETE CASCADE,
  reminder_id UUID REFERENCES medicine_reminders(id),
  scheduled_time TIMESTAMPTZ NOT NULL,
  taken_at TIMESTAMPTZ, -- NULL if missed
  is_taken BOOLEAN DEFAULT false,
  is_missed BOOLEAN DEFAULT false,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Medicine orders
CREATE TABLE medicine_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  order_number TEXT UNIQUE NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled')),
  delivery_address TEXT,
  pharmacy_name TEXT,
  pharmacy_contact TEXT,
  ordered_at TIMESTAMPTZ DEFAULT NOW(),
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Medicine order items
CREATE TABLE medicine_order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES medicine_orders(id) ON DELETE CASCADE,
  medicine_catalog_id UUID REFERENCES medicine_catalog(id),
  medicine_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  total_price DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 11.6 AI Assistant
-- ============================================================

-- AI chat conversations
CREATE TABLE ai_chat_conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  title TEXT, -- Auto-generated from first message
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- AI chat messages
CREATE TABLE ai_chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES ai_chat_conversations(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  metadata JSONB, -- For storing action results, context, etc.
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 11.7 Notifications
-- ============================================================

-- Notification log
CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('medicine_reminder', 'consultation_reminder', 'health_alert', 'ble_status', 'general')),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  data JSONB, -- Additional data for deep linking, etc.
  is_read BOOLEAN DEFAULT false,
  read_at TIMESTAMPTZ,
  is_delivered BOOLEAN DEFAULT false,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 11.8 Emergency Logs
-- ============================================================

-- Emergency activation log
CREATE TABLE emergency_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  triggered_at TIMESTAMPTZ DEFAULT NOW(),
  location_latitude DECIMAL(10,8),
  location_longitude DECIMAL(11,8),
  location_address TEXT,
  health_status_snapshot JSONB, -- Current health metrics at time of emergency
  emergency_number_called TEXT,
  caregiver_notified BOOLEAN DEFAULT false,
  caregiver_notification_details JSONB,
  is_false_alarm BOOLEAN DEFAULT false,
  resolved_at TIMESTAMPTZ,
  notes TEXT
);

-- ============================================================
-- 11.9 Indexes for Performance
-- ============================================================

-- Health metrics indexes
CREATE INDEX idx_health_metrics_user_date ON health_metrics(user_id, recorded_at DESC);
CREATE INDEX idx_health_metrics_type ON health_metrics(metric_type);

-- Health alerts indexes
CREATE INDEX idx_health_alerts_user_unread ON health_alerts(user_id, is_read) WHERE is_read = false;

-- Consultations indexes
CREATE INDEX idx_consultations_user_status ON consultations(user_id, status);
CREATE INDEX idx_consultations_date ON consultations(appointment_date, appointment_time);

-- Medicine reminders indexes
CREATE INDEX idx_medicine_reminders_active ON medicine_reminders(is_active) WHERE is_active = true;

-- Notifications indexes
CREATE INDEX idx_notifications_user_unread ON notifications(user_id, is_read) WHERE is_read = false;

-- BLE devices indexes
CREATE INDEX idx_ble_devices_user_active ON ble_devices(user_id, is_active) WHERE is_active = true;

-- ============================================================
-- 11.10 Row Level Security (RLS) Policies
-- ============================================================

-- Enable RLS on all tables
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE ble_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE medical_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_medicines ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicine_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicine_intake_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicine_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_chat_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE emergency_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only access their own data
CREATE POLICY "Users can view own profile" ON user_profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON user_profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can manage own settings" ON user_settings FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own BLE devices" ON ble_devices FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own health metrics" ON health_metrics FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own health alerts" ON health_alerts FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own consultations" ON consultations FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own medical records" ON medical_records FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own medicines" ON user_medicines FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own reminders" ON medicine_reminders FOR ALL USING (auth.uid() = (SELECT user_id FROM user_medicines WHERE id = user_medicine_id));
CREATE POLICY "Users can manage own intake log" ON medicine_intake_log FOR ALL USING (auth.uid() = (SELECT user_id FROM user_medicines WHERE id = user_medicine_id));
CREATE POLICY "Users can manage own orders" ON medicine_orders FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own AI conversations" ON ai_chat_conversations FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own notifications" ON notifications FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own emergency logs" ON emergency_logs FOR ALL USING (auth.uid() = user_id);

-- Public read access for catalogs
ALTER TABLE specialties ENABLE ROW LEVEL SECURITY;
ALTER TABLE doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicine_catalog ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view specialties" ON specialties FOR SELECT USING (true);
CREATE POLICY "Public can view doctors" ON doctors FOR SELECT USING (true);
CREATE POLICY "Public can view medicine catalog" ON medicine_catalog FOR SELECT USING (true);

